// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micro/go-micro/api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type Pair struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               string   `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Pair) GetValues() string {
	if m != nil {
		return m.Values
	}
	return ""
}

type GetUserByIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdRequest) Reset()         { *m = GetUserByIdRequest{} }
func (m *GetUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdRequest) ProtoMessage()    {}
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdRequest.Unmarshal(m, b)
}
func (m *GetUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdRequest.Merge(m, src)
}
func (m *GetUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdRequest.Size(m)
}
func (m *GetUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdRequest proto.InternalMessageInfo

func (m *GetUserByIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserByIdResponse struct {
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	User *User  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// map
	Header               map[string]*Pair `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetUserByIdResponse) Reset()         { *m = GetUserByIdResponse{} }
func (m *GetUserByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdResponse) ProtoMessage()    {}
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetUserByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdResponse.Unmarshal(m, b)
}
func (m *GetUserByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdResponse.Merge(m, src)
}
func (m *GetUserByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdResponse.Size(m)
}
func (m *GetUserByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdResponse proto.InternalMessageInfo

func (m *GetUserByIdResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetUserByIdResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetUserByIdResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserByIdResponse) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.user.User")
	proto.RegisterType((*Pair)(nil), "go.micro.srv.user.Pair")
	proto.RegisterType((*GetUserByIdRequest)(nil), "go.micro.srv.user.GetUserByIdRequest")
	proto.RegisterType((*GetUserByIdResponse)(nil), "go.micro.srv.user.GetUserByIdResponse")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.srv.user.GetUserByIdResponse.HeaderEntry")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xeb, 0x40,
	0x14, 0xc5, 0x5f, 0xfe, 0x34, 0xef, 0xe5, 0x06, 0x1e, 0x3a, 0x82, 0x0d, 0x75, 0x53, 0x82, 0x4a,
	0x41, 0x3a, 0x95, 0xb8, 0x11, 0x97, 0x82, 0x68, 0x45, 0x44, 0x46, 0xdc, 0x2a, 0x69, 0x72, 0x49,
	0x07, 0x4d, 0xa7, 0xce, 0x24, 0x85, 0x7e, 0x03, 0x3f, 0xb6, 0xcc, 0x4d, 0x85, 0xaa, 0x05, 0xdd,
	0x9d, 0x99, 0x7b, 0xe6, 0xdc, 0x5f, 0x0e, 0x01, 0x68, 0x0c, 0x6a, 0x3e, 0xd7, 0xaa, 0x56, 0x6c,
	0xbb, 0x54, 0xbc, 0x92, 0xb9, 0x56, 0xdc, 0xe8, 0x05, 0xb7, 0x83, 0xde, 0xb0, 0x94, 0xf5, 0xb4,
	0x99, 0xf0, 0x5c, 0x55, 0x23, 0x1a, 0x8d, 0x4a, 0x35, 0x6c, 0x45, 0x36, 0x97, 0x23, 0x7a, 0x67,
	0x55, 0x9b, 0x90, 0xdc, 0x80, 0xff, 0x60, 0x50, 0xb3, 0xff, 0xe0, 0xca, 0x22, 0x76, 0xfa, 0xce,
	0xc0, 0x13, 0xae, 0x2c, 0x58, 0x17, 0xfe, 0xda, 0xb8, 0x27, 0x59, 0xc4, 0x6e, 0xdf, 0x19, 0x84,
	0x22, 0xb0, 0xc7, 0x71, 0xc1, 0xf6, 0x20, 0xa4, 0xc1, 0x2c, 0xab, 0x30, 0xf6, 0x68, 0xf4, 0xcf,
	0x5e, 0xdc, 0x66, 0x15, 0x26, 0xc7, 0xe0, 0xdf, 0x65, 0x52, 0xb3, 0x2d, 0xf0, 0x9e, 0x71, 0x49,
	0x71, 0x1d, 0x61, 0x25, 0xdb, 0x85, 0x60, 0x91, 0xbd, 0x34, 0x68, 0x3e, 0xe2, 0xda, 0x53, 0xb2,
	0x0f, 0xec, 0x12, 0x6b, 0x8b, 0x70, 0xbe, 0x1c, 0x17, 0x02, 0x5f, 0x1b, 0x34, 0xf5, 0x57, 0x9a,
	0xe4, 0xcd, 0x85, 0x9d, 0x4f, 0x36, 0x33, 0x57, 0x33, 0x83, 0x8c, 0x81, 0x9f, 0xab, 0x02, 0xc9,
	0x19, 0x0a, 0xd2, 0x76, 0x77, 0x65, 0xca, 0xd5, 0x1a, 0x2b, 0xd9, 0x11, 0xf8, 0x96, 0x90, 0x68,
	0xa3, 0xb4, 0xcb, 0xbf, 0x95, 0xc6, 0x6d, 0xb0, 0x20, 0x13, 0xbb, 0x86, 0x60, 0x8a, 0x59, 0x81,
	0x3a, 0xf6, 0xfb, 0xde, 0x20, 0x4a, 0xd3, 0x0d, 0xf6, 0x0d, 0x28, 0xfc, 0x8a, 0x1e, 0x5d, 0xcc,
	0x6a, 0xbd, 0x14, 0xab, 0x84, 0x9e, 0x80, 0x68, 0xed, 0x7a, 0xbd, 0x95, 0xb0, 0x6d, 0x65, 0x08,
	0x1d, 0xea, 0x81, 0x68, 0x37, 0xa3, 0xd9, 0x3e, 0x45, 0xeb, 0x3a, 0x73, 0x4f, 0x9d, 0xb4, 0x82,
	0xc8, 0xee, 0xbe, 0x47, 0xbd, 0x90, 0x39, 0xb2, 0x47, 0x88, 0xd6, 0x68, 0xd8, 0xc1, 0x4f, 0xb4,
	0xd4, 0x6f, 0xef, 0xf0, 0x77, 0x1f, 0x95, 0xfc, 0x99, 0x04, 0xf4, 0x9b, 0x9c, 0xbc, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xa2, 0x0f, 0x25, 0x05, 0x76, 0x02, 0x00, 0x00,
}
